// <auto-generated />
namespace SMUEE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IdentitySetUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitySetUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202112062240256_IdentitySetUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
