//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_LKP_ALTA
    {
        public byte PK_Alta { get; set; }
        public string DE_Alta { get; set; }
        public string CO_TEDS { get; set; }
        public string CO_TEDS_MH { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ordered { get; set; }
        public string CW_COMENTARIO { get; set; }
    }
}
