//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_PERFIL_ELIMINADO
    {
        public int PK_PERFIL_ELIMINADO { get; set; }
        public string STATE_CODE { get; set; }
        public string STATE_PROVIDER { get; set; }
        public string CLIENT_IDENTIFIER { get; set; }
        public string CODEPENDENT_COLATERAL { get; set; }
        public string CLIENT_TRANSACTION_TYPE { get; set; }
        public string DATE_OF_ADMISION { get; set; }
        public string TYPE_OF_TREATMENT { get; set; }
        public string DATE_LAST_CONTACT { get; set; }
        public string DATE_OF_DISCHARGE { get; set; }
        public Nullable<int> FK_EPISODIO { get; set; }
        public Nullable<int> FK_PERFIL { get; set; }
        public string TIPO_PERFIL { get; set; }
        public Nullable<int> FK_ESTATUS_PERFIL_TEDS { get; set; }
        public Nullable<System.DateTime> FE_ENVIADO_A_TEDS { get; set; }
        public string TEDS_ID { get; set; }
        public Nullable<System.DateTime> FE_SUBIDO_ACEPTADO_POR_TEDS { get; set; }
        public Nullable<System.Guid> FK_SESION { get; set; }
    }
}
