//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_HISTORIAL
    {
        public int PK_Historial { get; set; }
        public string FK_Sesion { get; set; }
        public Nullable<System.DateTime> FE_Historial { get; set; }
        public string DE_Historial { get; set; }
        public Nullable<byte> TI_ACCION { get; set; }
        public string FK_Modulo { get; set; }
    
        public virtual SM_MODULO SM_MODULO { get; set; }
    }
}
