//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_LKP_ICONO_NOTIFICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_LKP_ICONO_NOTIFICACIONES()
        {
            this.SM_NOTIFICACIONES = new HashSet<SM_NOTIFICACIONES>();
        }
    
        public int PK_ICONO { get; set; }
        public string COLOR_ICONO { get; set; }
        public string NB_ICONO { get; set; }
        public string DE_ICONO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SM_NOTIFICACIONES> SM_NOTIFICACIONES { get; set; }
    }
}
