//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_SC_VW_RPT_TEDS_MH_AD
    {
        public string System_Transaction_Type { get; set; }
        public string State_Code { get; set; }
        public string Reporting_Date { get; set; }
        public string Provider_Identifier { get; set; }
        public string Client_Identifier { get; set; }
        public string Co_Dependant { get; set; }
        public string Client_Transaction_Type { get; set; }
        public string Date_of_Admision { get; set; }
        public string Type_of_Service { get; set; }
        public string Num_of_Prior_Treat_Episode { get; set; }
        public string Principal_Source_of_Referral { get; set; }
        public string Date_of_Birth { get; set; }
        public string Sex { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string Education { get; set; }
        public string Employment_Status { get; set; }
        public string Substance_Pro_Code_Primary { get; set; }
        public string Usual_Route_of_Admin_Primary { get; set; }
        public string Frecuency_of_Use_Primary { get; set; }
        public string Age_of_First_Use_Primary { get; set; }
        public string Substance_Pro_Code_Secondary { get; set; }
        public string Usual_Route_of_Admin_Secondary { get; set; }
        public string Frecuency_of_Use_Secondary { get; set; }
        public string Age_of_First_Use_Secondary { get; set; }
        public string Substance_Pro_Code_Tertiary { get; set; }
        public string Usual_Route_of_Admin_Tertiary { get; set; }
        public string Frecuency_of_Use_Tertiary { get; set; }
        public string Age_of_First_Use_Tertiary { get; set; }
        public string Opioid_Replacement_Therapy { get; set; }
        public string Detailed_Drug_Code_Primary { get; set; }
        public string Detailed_Drug_Code_Secondary { get; set; }
        public string Detailed_Drug_Code_Tertiary { get; set; }
        public string DSM_Diagnosis { get; set; }
        public string Co_occuring_Substance_Abuse_and_Mental_Health_Problems { get; set; }
        public string Pregnant_at_Time_of_Admision { get; set; }
        public string Veteran_Status { get; set; }
        public string Living_Arrangements { get; set; }
        public string Source_of_Income_Support { get; set; }
        public string Health_Insurance { get; set; }
        public string Expected_Actual_Primary_Source_of_Payment { get; set; }
        public string Detailed_Not_In_Labor_Force { get; set; }
        public string Detailed_Criminal_Justice_Referral { get; set; }
        public string Maritial_Status { get; set; }
        public string Days_Waiting_to_Enter_Treatment { get; set; }
        public string Number_of_Arrests_in_30_Days_Prior_Adm { get; set; }
        public string Frequency_of_Attendance { get; set; }
        public string Diagnostic_Code_Set_Identifier { get; set; }
        public string Substance_Abuse_Diagnostic_ICD_10 { get; set; }
        public string MH_Diag_Code_Primary_ICD_10 { get; set; }
        public string MH_Diag_Code_Secondary_ICD_10 { get; set; }
        public string MH_Diag_Code_Tertiary_ICD_10 { get; set; }
        public string Smi_Sed_Status { get; set; }
        public string School_Attendance_Status { get; set; }
        public string Legal_Status_at_Admission_State_Hospital { get; set; }
        public string Escala_GAF { get; set; }
        public int Perfil { get; set; }
        public int Episode { get; set; }
    }
}
