//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOCUMENTOS
    {
        public int PK_DOCUMENTO { get; set; }
        public string NB_DOCUMENTO { get; set; }
        public string DE_DOCUMENTO { get; set; }
        public string PATH_DOCUMENTO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string FK_MODULO { get; set; }
    }
}
