//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EPISODIO
    {
        public int PK_Episodio { get; set; }
        public int FK_Persona { get; set; }
        public short FK_Programa { get; set; }
        public string NB_Programa { get; set; }
        public Nullable<System.DateTime> FE_FechaConvenio { get; set; }
        public byte PK_Administracion { get; set; }
        public string NB_Administracion { get; set; }
        public System.DateTime FE_Episodio { get; set; }
        public byte FK_SeguroSalud { get; set; }
        public string DE_SeguroSalud { get; set; }
        public byte FK_FuentePago { get; set; }
        public string DE_Pago { get; set; }
        public byte FK_FeminaHijos { get; set; }
        public string DE_Femina { get; set; }
        public Nullable<byte> IN_VaronHijos { get; set; }
        public string DE_VaronHijos { get; set; }
        public byte FK_FuenteIngreso { get; set; }
        public string DE_FuenteIngreso { get; set; }
        public Nullable<byte> FK_IngresoIndividual { get; set; }
        public string DE_IngresoAnualIndividual { get; set; }
        public Nullable<byte> FK_IngresoFamiliar { get; set; }
        public string DE_IngresoAnualFamiliar { get; set; }
        public byte FK_TiempoResidencia { get; set; }
        public string DE_TiempoResidencia { get; set; }
        public short FK_Municipio { get; set; }
        public string DE_Municipio { get; set; }
        public byte IN_Zona { get; set; }
        public string DE_Zona { get; set; }
        public string NR_ZipCode { get; set; }
        public string DE_Barrio { get; set; }
        public byte FK_EtapaServicio { get; set; }
        public string DE_EtapaServicio { get; set; }
        public Nullable<byte> FK_NivelCuidadoSustancias { get; set; }
        public string DE_AbusoSustancias { get; set; }
        public Nullable<byte> FK_NivelCuidadoMental { get; set; }
        public string DE_SaludMental { get; set; }
        public byte IN_Metadona { get; set; }
        public string DE_Metadona { get; set; }
        public byte IN_CodDependiente { get; set; }
        public string DE_CodDependiente { get; set; }
        public Nullable<byte> IN_DiagnosticoDual { get; set; }
        public string DE_DiagnosticoDual { get; set; }
        public byte FK_FuenteReferido { get; set; }
        public string DE_Referido { get; set; }
        public byte FK_EstadoLegal { get; set; }
        public string DE_EstadoLegal { get; set; }
        public byte IN_ArrestadoAnteriormente { get; set; }
        public string DE_ArrestadoAnteriormente { get; set; }
        public Nullable<byte> NR_TotalArrestosPasado { get; set; }
        public byte FK_Justicia { get; set; }
        public string DE_ProbJusticia { get; set; }
        public Nullable<short> NR_DiasEsperaSustancias { get; set; }
        public byte FK_EpisodiosSustancias { get; set; }
        public string DE_EpisodiosPreviosSustancias { get; set; }
        public byte FK_DuracionSustancias { get; set; }
        public string DE_TiempoUltTratSustancias { get; set; }
        public Nullable<short> NR_DiasUltimaAltaSustancias { get; set; }
        public Nullable<short> NR_MesesUltimaAltaSustancias { get; set; }
        public byte FK_NivelCuidadoSustanciasAnterior { get; set; }
        public string DE_AbusoSustanciasAnterior { get; set; }
        public Nullable<byte> IN_SaludMental { get; set; }
        public string DE_IN_SaludMental { get; set; }
        public Nullable<short> NR_DiasEsperaMental { get; set; }
        public byte FK_EpisodiosMental { get; set; }
        public string DE_EpisodiosPreviosMental { get; set; }
        public byte FK_DuracionMental { get; set; }
        public string DE_TiempoUltTratMental { get; set; }
        public Nullable<short> NR_DiasUltimaAltaMental { get; set; }
        public Nullable<short> NR_MesesUltimaAltaMental { get; set; }
        public byte FK_NivelCuidadoMentalAnterior { get; set; }
        public string DE_SaludMentalAnterior { get; set; }
        public Nullable<byte> IN_AbusoSustancias { get; set; }
        public string DE_IN_AbusoSustancias { get; set; }
        public byte IN_ViolenciaDomestica { get; set; }
        public string DE_ViolenciaDomestica { get; set; }
        public byte IN_Maltrato { get; set; }
        public string DE_Maltrato { get; set; }
        public byte IN_TI_Maltrato { get; set; }
        public string DE_TI_Maltrato { get; set; }
        public string DE_Suicida { get; set; }
        public Nullable<byte> IN_TratadoMental { get; set; }
        public string DE_TratadoMental { get; set; }
        public Nullable<byte> IN_Ambulatorio { get; set; }
        public string DE_Ambulatorio { get; set; }
        public Nullable<byte> IN_HospitalizadoMental { get; set; }
        public string DE_HospitalizadoMental { get; set; }
        public Nullable<byte> IN_TI_Hospital { get; set; }
        public string DE_TI_Hospital { get; set; }
        public Nullable<byte> IN_TratamientoResidencial { get; set; }
        public string DE_TratamientoResidencial { get; set; }
        public Nullable<bool> ES_Episodio { get; set; }
        public string DE_ES_Episodio { get; set; }
        public Nullable<byte> IN_IdeaSuicida { get; set; }
        public string DE_IdeaSuicida { get; set; }
        public byte IN_Suicida { get; set; }
        public Nullable<System.DateTime> FE_Alta { get; set; }
    }
}
