//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPEDIENTE_PROGRAMA
    {
        public int FK_Persona { get; set; }
        public short FK_Programa { get; set; }
        public string NR_Expediente { get; set; }
        public System.Guid FK_Sesion { get; set; }
        public string TI_Edicion { get; set; }
        public System.DateTime FE_Edicion { get; set; }
        public Nullable<int> PK_Old { get; set; }
        public string NR_SeguroSocial { get; set; }
        public byte FK_Sexo { get; set; }
        public string AP_Primero { get; set; }
        public string AP_Segundo { get; set; }
        public string NB_Primero { get; set; }
        public string NB_Segundo { get; set; }
        public System.DateTime FE_Nacimiento { get; set; }
        public byte FK_Veterano { get; set; }
        public byte FK_GrupoEtnico { get; set; }
        public string NR_ClientId_Legacy { get; set; }
        public byte FK_Administracion { get; set; }
        public Nullable<short> CO_Tipo { get; set; }
        public string CO_Programa { get; set; }
        public string CO_Prov_ID { get; set; }
        public string NB_Programa { get; set; }
        public string DE_Programa { get; set; }
        public string NB_ProgramaIngles { get; set; }
        public string CO_Hacienda { get; set; }
        public bool IN_Inactivo { get; set; }
        public bool IN_Creado_Fed { get; set; }
        public bool IN_TEDS { get; set; }
        public Nullable<bool> REP_TEDS { get; set; }
        public Nullable<bool> PREOW { get; set; }
        public Nullable<bool> IN_SUST { get; set; }
        public Nullable<bool> IN_INF_ANUAL { get; set; }
        public Nullable<bool> REP_TEDS_MH { get; set; }
        public Nullable<bool> IN_SELECCIONADO_REP { get; set; }
        public Nullable<bool> IN_CONVENIO { get; set; }
        public Nullable<bool> REP_URS_MH { get; set; }
        public Nullable<int> FK_CATEGORIA_PROGRAMA { get; set; }
    }
}
