//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NOTIFICACIONES
    {
        public int PK_NOTIFICACIONES { get; set; }
        public string DE_NOTIFICACIONES { get; set; }
        public Nullable<System.DateTime> FE_ENVIADO { get; set; }
        public string TITULO { get; set; }
        public Nullable<int> FK_ICONO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string COLOR_ICONO { get; set; }
        public string NB_ICONO { get; set; }
        public string DE_ICONO { get; set; }
    }
}
