//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PROGRAMAS
    {
        public short PK_Programa { get; set; }
        public byte FK_Administracion { get; set; }
        public string CO_Programa { get; set; }
        public string NB_Programa { get; set; }
        public bool IN_Creado_Fed { get; set; }
        public bool IN_TEDS { get; set; }
        public Nullable<bool> REP_TEDS { get; set; }
        public Nullable<bool> IN_SUST { get; set; }
    }
}
