//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REF_SALUD_MENTAL
    {
        public int PK_Item { get; set; }
        public int PK_Programa { get; set; }
        public int PK_Mental { get; set; }
        public bool Active { get; set; }
        public string DE_SaludMental { get; set; }
        public string CO_TEDS_MH { get; set; }
    }
}
