//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REPORTES
    {
        public int PK_REPORTES { get; set; }
        public string NB_REPORTE { get; set; }
        public string DE_REPORTE { get; set; }
        public string NB_SSRS_REPORTE { get; set; }
        public int PK_CATEGORIA_REPORTE { get; set; }
        public string NB_CATEGORIA_REPORTE { get; set; }
        public string MODULO_REPORTE { get; set; }
    }
}
