//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAEP
    {
        public string Nombre_Programa { get; set; }
        public string Nombre_Participante { get; set; }
        public int IUP { get; set; }
        public string Expediente { get; set; }
        public int Número_de_Episodio { get; set; }
        public System.DateTime Fecha_Admsión { get; set; }
        public Nullable<System.DateTime> ÚltimoPerfil { get; set; }
        public string Tipo_de_Último_Perfil { get; set; }
        public Nullable<int> Meses_sin_Perfiles_de_Evaluación_de_Progreso { get; set; }
        public short FK_Programa { get; set; }
        public int PK_NR_Perfil { get; set; }
    }
}
