//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UsersList
    {
        public string ImgPerfil { get; set; }
        public string Usuario { get; set; }
        public string Email { get; set; }
        public string Rol { get; set; }
        public string PK_Usuario { get; set; }
        public string Modulos { get; set; }
        public string Confirmado { get; set; }
        public string Estatus { get; set; }
    }
}
